### ISSUE TITLE
Cant extract models

### ISSUE THREAD

**Issue by superdotaplaya** [Kattoor/nw-model-miner#4]
The datatables are being extracted properly, but I keep getting this error when it moves onto the models, not sure whats causing this to happen.

`TypeError: Cannot read properties of undefined (reading 'skin1')
    at extractAndAssemble (file:///C:/Users/main/Desktop/nw-model-miner-master/models/extract-and-assemble.mjs:81:49)
    at async file:///C:/Users/main/Desktop/nw-model-miner-master/nw-model-miner.mjs:30:1`

**Comment by PotatoMastah** [comment]
![image](https://user-images.githubusercontent.com/103550576/163091955-71511fa5-4666-469c-a34a-0e8f9bdce14d.png)
I'm having the same issue, maybe the game changed some data structure?

**Comment by darealsenor** [comment]
> ![image](https://user-images.githubusercontent.com/103550576/163091955-71511fa5-4666-469c-a34a-0e8f9bdce14d.png) I'm having the same issue, maybe the game changed some data structure?

Any updates? Having the same error

**Comment by filibis** [comment]
Hey @Kattoor @superdotaplaya @PotatoMastah @darealsenor could you resolve this issue? I'm having the same error.

**Comment by bsungur** [comment]
Ran into the same error. When I looked into it it seemed like the csv indexes were off for the itemdefinition csvs in extract-and-assemble.mjs.

[https://github.com/Kattoor/nw-model-miner/compare/master...bsungur:nw-model-miner:4-fix-csv-indexes?expand=1#diff-47834fc33c7c227f9541f1769309b5d3951a8650251e2a2b0f8062b83fec1cae](https://github.com/Kattoor/nw-model-miner/compare/master...bsungur:nw-model-miner:4-fix-csv-indexes?expand=1#diff-47834fc33c7c227f9541f1769309b5d3951a8650251e2a2b0f8062b83fec1cae)

The script completed with the changes I made, but all the models seemed jumbled up in the viewer. I don't know what else is going on here.

**Comment by filibis** [comment]
Direct hit @bsungur ! I could successfully export the data as well (but only .dae, glTF part still gives error). Thank you for the finding and sharing.
Also do you know why there is no 3D architectural elements exporting? I can only see characters and items exported. Is it possible to extract houses, walls, gates etc.?

**Comment by bsungur** [comment]
Thanks for confirming @filibis. 

I also noticed that it seemed only the armor models were exporting. I am also more interested in some of the other models, maybe things like housing trophies. Unfortunately I don't know my way around the datasheets or this tool very well.
