### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'skin1')

### ISSUE THREAD

**Issue by Dizcordum** [Kattoor/nw-model-miner#7]
D:\UTILITES\python>node nw-model-miner.mjs "D:\NWpak"
Extracting datasheets.. finished in 9442ms
Converting datasheets.. finished in 4371ms
Dumping headers.. finished in 33598ms
file:///D:/UTILITES/python/models/extract-and-assemble.mjs:82
-----------------------------model: itemAppearanceDefinition.skin1,
-(i placed - symbol so it shows as in console)-----------------^

TypeError: Cannot read properties of undefined (reading 'skin1')
    at extractAndAssemble (file:///D:/UTILITES/python/models/extract-and-assemble.mjs:82:38)
    at async file:///D:/UTILITES/python/nw-model-miner.mjs:30:1
Node.js v18.13.0

It stops at reading skin data

**Comment by VirtualMafia** [comment]
How did you even get this far? Im stuck just getting Node to even start the script. Any hints?

**Comment by Dizcordum** [comment]
> How did you even get this far? Im stuck just getting Node to even start the script. Any hints?

cuz it is probalby outdated by now
